### ISSUE TITLE
OTG Adapter in Prog port only allows PS4 controller

### ISSUE THREAD

**Issue by ghost** [J2Kbr/TitanTwo#156]
When connecting the Titan Two to a console via the Output port and using an OTG adapter in the Prog port to connect a third input, only an official PS4 controller is accepted, an Xbox One controller for example will not work and the Prog light will appear red.

I have tested this with multiple Titan Two's and on multiple consoles with but always the same result. Is this the intended behavior, or should it work the same as Input-A/B?

**Comment by ghost** [comment]
This is with the latest firmware and the official OTG adapter that is included in the connection kit.

**Comment by J2Kbr** [comment]
The PROG-OTG port only supports HID compatible controllers. The reason for that is because the PROG is connected direct to the CPU. Therefore, separated from the main USB controller, which does not permit the pass-trough modes and would require implementation of duplicated drivers for each protocol. For that reason only the HID driver was implemented for the PROG-OTG port.
