### ISSUE TITLE
port_connect should actually change the output for the entire device

### ISSUE THREAD

**Issue by PablosScripts** [J2Kbr/TitanTwo#201]
I used this script: 

https://www.consoletuner.com/forum/viewtopic.php?f=27&t=11563#p78656

And I thought it wasn't working, until I read this comment from Scachi: 

https://www.consoletuner.com/forum/viewtopic.php?f=27&t=11563&start=10#p78757

It seems it IS working, but it won't show in Gtuner IV or Gtuner Air. I think it should set it permanently and you should be able to see this in both apps. Otherwise it is very confusing for users which output protocol they are actually using.

**Comment by J2Kbr** [comment]
As general rule commands executed by GPC scripts are valid only during the life time of the script. When the script is unloaded, the device returns to its "default" state, which are defined by the user's defined configurations.

Please note there no GPC command that is able to overwrite any device configuration set by the user. Otherwise, a downloaded script could -for example- overwrite the output protocol without warning the user, making he wondering why the device is not working anymore on his console even when there is no script running (memory slot 0).
