### ISSUE TITLE
USB cable connectivity

### ISSUE THREAD

**Issue by digitalzombie** [J2Kbr/TitanTwo#21]
While testing the unit with different micro USB to USB cables I have found out that the unit worked only with the cable that it was shipped. 3 other micro USB to USB cables that I have laying around which also work with Titan One, does not seem to work with this device. Gtuner does not detect the unit with the other cables.

**Comment by digitalzombie** [comment]
Other USB cables which provide power but no connectivity actually allow Titan Two to connect to Gtuner IV for a split second and then the device gets immediately
![titan2](https://cloud.githubusercontent.com/assets/7460940/19831937/1b2afd66-9dcb-11e6-9169-80f651e63786.PNG)
 disconnected.

**Comment by omasseau** [comment]
I also had connectivity problem but with the USB cable coming with the Titan Two.

When using it with my PS4 (Xbox 360 controller connected on Input A and PS4 controller connected on Input B), I was disconnected every 30s with the output led becoming red.

I replaced it with the USB cable of my Nexus 7 and everything works fine now.

**Comment by J2Kbr** [comment]
Correct. Most connectivity issues reported so far are related with low quality USB cables. The one provided with Titan Two will be replaced in the next production batch. A good quality cable is important specially for the PROG connection, as this is a high speed USB link (480Mbps) and any external interference can lead to disconnections.

As this issue is not related to the firmware, I am closing.
