### ISSUE TITLE
Support for Steam controller over Bluetooth with BLE

### ISSUE THREAD

**Issue by nelsontm** [J2Kbr/TitanTwo#229]
Support for the Steam controller over Bluetooth with the BLE [https://support.steampowered.com/kb_article.php?ref=7728-QESJ-4420](url) added to the Steam controller last year. The input protocol might be the same as the wireless receiver and USB mode since it works the same way on PC, but the Steam controller wouldn’t pair with the Titan Two in BLE mode.

**Comment by J2Kbr** [comment]
Thank you for your suggestion and bringing this information to my attention.

The BLE interface on the Titan Two is dedicated for Gtuner Air connectivity. With current implementation the BLE interface can't handle connections for input devices, such as controllers.

In addition to that, the BLE interface is not suitable for gameplay, its has very low bandwidth and no guarantee of response time (the latency can easily reach dozens of milliseconds). I am surprised the Steam controller opted for BLE instead of regular BRE/EDR (like PS4 and Switch controllers).

The Steam controller can already be used wirelessly with the Titan Two using the provided Steam controller USB dongle.
