### ISSUE TITLE
Headphone noise when using script on xbox series x , no noise on ps4pro

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/TitanTwo#280]
I have someone reporting issues when using a script that adds T2 cpu load around 20%, get get crackling using the xbox series X: report: "when the cpu rises to 15-18 there is some kind of crackling in the ears"

He tested the same script on the ps4pro with a headset connected to the controller and there no noise issue appears.
Script attached.

His configuration:
the mouse is connected to A, the gamepad is connected to B, the keyboard to the laptop and through the capture in gtuner

[ARMulti_102.zip](https://github.com/J2Kbr/TitanTwo/files/5620233/ARMulti_102.zip)

**Comment by J2Kbr** [comment]
Some optimizations were made on FW 1.11 in order to forward audio data packets between the console and controllers more efficiently, in attempt to avoid the reported issue. However, high CPU usage can still/occasionally causing delay on this data forwarding as all internal processes are handled by the system loop, if any delay is caused by a particular process (e.g. script) it will affect the performance of others processes.
