### ISSUE TITLE
PS4 with DualSense Wireless = inconsistent rumbling on dual sense

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/TitanTwo#284]
Running firmware: 1.10.3.0
BT-A : ds4v1
BT-B : dual sense
Output: PS4 pro
Prog: pc

Playing "The Division 1", shooting a full 66bullet clip with my favorite weapon "lvoa-c", my ds4v1 controller rumbles the whole time when firing a complete clip like the graph is showing.
But the "dual sense" ps5 controller stops vibrating for short periods in between, Looks like there is some timing issue with the rumble commands for the ps5 controller on ps4.

Green is the rumble of the ds4v1 for the whole  clip, orange is the dual sense (the pause of that rumble variates a bit)
![image](https://user-images.githubusercontent.com/22262242/103217796-c569fe00-4919-11eb-8d3e-c8595455caf7.png)

Another question: Is it normal that the duration is always reported as 500 on the ps4 ?

**Comment by J2Kbr** [comment]
Hi Scachi,

After some testing (without being able to reproduce the issue). I believe the problem is related with Bluetooth (perhaps saturation of Bluetooth bandwidth as you have 2 controllers connected at the same time). Please first try wired to check if the problem still occurs, then only with the DualSense wirelessly (keeping the DS4 wired).

Thanks.
