### ISSUE TITLE
(Feature Request) Retron5 output over bluetooth.

### ISSUE THREAD

**Issue by CrispyPixels** [J2Kbr/TitanTwo#32]
The Retron5 is a great console if you like old games, but to say the controllers suck would be a massive improvement. Since they work over bluetooth, it would be awesome if the Titan 2 would support this output.

**Comment by J2Kbr** [comment]
Thank you for your suggestion. After some researching it seems it will be needed implement a full emulator of the Retron5 gamepad in order to support this console. My hope was Retron5 to support some common controller such as Wii U Pro, PS3, PS4, etc, so you would use an already available output protocol on the Titan Two to play on this console.

A full emulator implementation occupy lot space on the Titan Two's firmware flash memory. As this is a very niche segment, with no demand among the majority of the Titan Two users, the best is save this space to support the upcoming PlayStation and Xbox.
