### ISSUE TITLE
(Feature Request) Crossover Support For The First Xbox

### ISSUE THREAD

**Issue by Dext1** [J2Kbr/TitanTwo#33]
I don't know if this is possible, but it would be really nice to be able to play some classic Xbox titles with new controllers + scripting support. I know you can get usb-adapters for the proprietary port on the first Xbox, but it only recognizes classic controllers.

**Comment by J2Kbr** [comment]
Yesterday I researched more about the original Xbox protocol and this controller implements an internal USB Hub, hiding behind it the interfaces needed to access the controller inputs. By design the Titan Two does not support USB Hub and any implementation related to this would require too many changes. On top of that the user would still an extra adapter to convert the proprietary connector to USB. At this point it does not seems the efforts will worth, as the demand for the original Xbox is low. I am putting this on hold for now. Thank you for the suggestion anyway.
