### ISSUE TITLE
Xbox One S Controller - Inconsistent FFB

### ISSUE THREAD

**Issue by J2Kbr** [J2Kbr/TitanTwo#44]
Reference:
http://www.consoletuner.com/forum/viewtopic.php?p=43989#p43989

> Any event that causes my controller to vibrate will cause my controller to vibrate as expected but the controller will continuously keep vibrating a lot longer than its suppose to.

**Comment by PablosScripts** [comment]
I may have some input into this. 

I have found something similar happening before when I've had too many devices connected to my T2. Once the vibration starts, it just never stops. Once I start unplugging more devices and there is a lower power draw, the problem goes away. I assume the AC power supply will fix this.

I find it's particular problematic with the PS4 controller as I think it has a higher power draw than the XB ones due to the lightbar and touchpad. 

IF this is the cause, I have an idea...maybe you could make a feature in Gtuner IV that allows you to monitor power usage. So you connect the T2 to a PC, connect all your accessories, and GTIV will tell you whether you should buy a power supply or not. This may help people with troubleshooting and prevent people from blaming the device when it could be a question of power draw.

**Comment by J2Kbr** [comment]
Issues with Xbox One S controller fixed on firmware 0.87B
