### ISSUE TITLE
Another E4 issue - custom controller

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/TitanTwo#66]
Learning to get the teensy 3.2 board to work for my snap-on device I managed to cause a E4 error multiple times.

I programmed the teensy 3.2 board with the keyboard example, using the board in "keyboard + mouse + joystick" mode and not as the example requires in keyboard mode only - by mistake.

I had my ds4 controller connected to input1, my pc connected to the prog port (but no gtuner running), a power supply connected to the titan two. This works just fine.
After connecting the teensy to input 2 I couldn't use the ds4 controller to navigate anymore, but both inputs still were green. After around a minute the T2 displayed the E4 error.

After reflashing the teensy in correct keyboard mode for the keyboard example everything seems to be working fine now.
I read in a teensy forum that using the teensy in joystick mode without initializing the analog sticks it can do some trouble. Maybe the E4 error happens because of to many crazy analog stick values read or submitted from an input port ?

I have not clue if that could be the cause, only the teensy forum post and my joystick mode issue made me think about this.

Feel free to mark this issue as garbage or nonsense if you like :-)

**Comment by J2Kbr** [comment]
Hi Scachi. My initial guess is the teensy, when incorrectly programmed, sends badly formatted data packets to the Titan Two which accumulates in memory until no more memory is available, causing E4.

As this does not happens when teensy is correctly programed, I am closing this issue, specially because I don't have a teensy to try replicate this problem to find a way to prevent the E4 error.
