### ISSUE TITLE
led_set "adding" brightness with "-" to default brightness

### ISSUE THREAD

**Issue by seededplyr** [J2Kbr/TitanTwo#98]
https://www.consoletuner.com/forum/viewtopic.php?f=27&t=7616

**Comment by J2Kbr** [comment]
I initially thought this issue was related with another. But after debugging the cause is indeed the constant calling of `led_set` while the button is pressed (`get_val`). `led_set` when called resets the duty cycle that dims the leds from the Titan Two's lightbar, not allowing enough time for off period, resulting is brighter color.

The solution is use `event_active` and `event_release` to call the `LED()` function, where is `led_set`.
